### ISSUE TITLE
Visual Studio 2015 support

### ISSUE THREAD

**Issue by MagicAndre1981** [pasztorpisti/vs-window-title-changer#1]
Do you have plans to support Visual Studio 2015?

**Comment by pasztorpisti** [comment]
I have no Win8 license and I would like to wait till Win10 release to buy one. A few weeks later I'll have a look, my guess would be that upgrading the plugin to VS2015 is easy, but this is just guessing.

**Comment by MagicAndre1981** [comment]
you don't need to buy anything. There is a free Community Edition of VS2015. It also runs on Windows 7 if you only build Desktop applications.

**Comment by pasztorpisti** [comment]
I totally misread the system requirements of VS2015. Unfortunately about half year ago when I moved abroad I signed away almost everything I had (including my PC with Win7). Since Win10 is released soon I'd wait for that instead of buying a license for 7 or 8.

**Comment by AHorak** [comment]
Yes, please add that feature.

**Comment by pasztorpisti** [comment]
It was enough to modify the vsixmanifest to get it work on VS2015. The settings UI looks a bit odd because the labels and buttons seem to be larger on Win10 for some reason and they overlap with other UI controls but this isn't a big issue.

**Comment by pasztorpisti** [comment]
fixed in bf21ed21cca915d444a0540ae668ed10e51ae07c

**Comment by pasztorpisti** [comment]
fixed in bf21ed21cca915d444a0540ae668ed10e51ae07c
